version: '3.9'

services:
    db:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=babelfishe

        build:
            context: ./db-mongo

        image: sv_db

        volumes:
            - type: volume
              source: vol-db
              target: /data/db

        ports:
            - target: 27017
              published: 27017

        networks:
            - net-pub

    be-auth:
        build:
            context: ./be-auth-dev

        image: sv_be-auth:dev

        ports:
            - target: 9001
              published: 9001

        networks:
            - net-pub

    be-campaigns:
        environment:
            - DB_RO=mongodb://adent:earth@db:27017/sillyvotes

        build:
            context: ./be-campaigns

        image: sv_be-campaigns

        ports:
            - target: 9002
              published: 9002

        networks:
            - net-pub

    fe-web-api:
        environment:
            - BE_AUTH_URL=http://be-auth:9001
            - BE_CAMPAIGNS_URL=http://be-campaigns:9002

        build:
            context: ./fe-web-api

        image: sv_fe-web-api

        ports:
            - target: 9000
              published: 9000

        networks:
            - net-pub

    fe-web:
        environment:
            - FE_WEB_API_URL=http://fe-web-api:9000

        build:
            context: ./fe-web-react

        image: sv_fe_web

        ports:
            - target: 8000
              published: 8000

        networks:
            - net-pub

volumes:
    vol-db:

networks:
    net-pub:
        name: silly-votes-net-pub
